server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: registration-service
          uri: lb://registration-service
          predicates:
            - Path=/auth/register,/auth/user

        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/auth/login

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka